apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealedsecret
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/obynodavid12/sealed-secrets'
    targetRevision: master
    directory:
      recurse: false
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false