apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeseal-app
  labels:
    app: kubeseal-app
  annotations:
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: kubeseal-app
  template:
    metadata:
      labels:
        app: kubeseal-app
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 3306
