apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secret
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: kubeseal-app
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd/kubeseal-app
    repoURL: 'https://github.com/obynodavid12/sealed-secrets.git'
    targetRevision: HEAD
    directory:
      recurse: true
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false